### ISSUE TITLE
Exception Cases in Service

### ISSUE THREAD

**Issue by shiminki** [Hanghae99-DoBlock/BE#11]
Exception case 포함하기 vs 없에기 (b/c front 에서 처리하니까)

**Comment by Ming-gry** [comment]
FE 와의 협의 결과, 예외 사항 (작성자가 아니거나, 피드를 찾을 수 없거나, 투두가 완료되지 않는 등) 에 대해 BE 에서 Double Check 하기로 결정되었습니다. 코드가 조금 길어질 수는 있겠지만 각자 맡은 사항에 대해 적용 부탁드립니다.
