### ISSUE TITLE
SdkClientException

### ISSUE THREAD

**Issue by shiminki** [Hanghae99-DoBlock/BE#20]
스프링 실행할때마다 초반에 SdkClientException 올라옴

com.amazonaws.SdkClientException: Failed to connect to service endpoint

**Comment by Ming-gry** [comment]
해당 에러는 EC2 인스턴스가 아닌 환경에서 실행할 때 발생하는 에러입니다. 어플리케이션이 작동하지 않는 등의 문제는 없습니다.
참고 : [https://earth-95.tistory.com/117](url)
